import 'dart:io';
import 'dart:math';
import 'package:path_provider/path_provider.dart';

class ModelService {
  static final ModelService _instance = ModelService._internal();
  factory ModelService() => _instance;
  ModelService._internal();
  
  List<Map<String, dynamic>> _models = [];
  String _activeModelId = '';
  bool _isInitialized = false;
  
  Future<void> init() async {
    if (_isInitialized) return;
    
    final dir = await getExternalStorageDirectory();
    final modelsDir = Directory('${dir?.path}/models');
    
    if (!await modelsDir.exists()) {
      await modelsDir.create(recursive: true);
    }
    
    // Demo models
    _models.add({
      'id': 'giant_x',
      'name': 'Giant Agent X',
      'path': null,
      'size': '2.5',
      'type': 'builtin',
      'status': 'available',
      'loaded': false,
    });
    
    _models.add({
      'id': 'phi_3',
      'name': 'Phi-3 Mini',
      'path': null,
      'size': '92',
      'type': 'tflite',
      'status': 'available',
      'loaded': false,
    });
    
    _models.add({
      'id': 'gemma',
      'name': 'Gemma 2B',
      'path': null,
      'size': '150',
      'type': 'tflite',
      'status': 'available',
      'loaded': false,
    });
    
    _activeModelId = _models.first['id'];
    _isInitialized = true;
  }
  
  List<Map<String, dynamic>> getModels() {
    return _models;
  }
  
  Map<String, dynamic> getActiveModel() {
    return _models.firstWhere((m) => m['id'] == _activeModelId, orElse: () => _models.first);
  }
  
  Future<bool> switchModel(String modelId) async {
    final model = _models.firstWhere((m) => m['id'] == modelId, orElse: () => {});
    if (model.isNotEmpty) {
      _activeModelId = modelId;
      return true;
    }
    return false;
  }
  
  Future<bool> loadModel(String modelId) async {
    final index = _models.indexWhere((m) => m['id'] == modelId);
    if (index != -1) {
      _models[index]['loaded'] = true;
      _models[index]['status'] = 'active';
      return true;
    }
    return false;
  }
  
  Future<String> generateResponse(String input) async {
    await Future.delayed(Duration(milliseconds: 500 + Random().nextInt(500)));
    
    final lower = input.toLowerCase();
    
    if (lower.contains('code') || lower.contains('كود')) {
      return _generateCode(input);
    } else if (lower.contains('site') || lower.contains('موقع') || lower.contains('html')) {
      return _generateWebsite(input);
    } else if (lower.contains('analyze') || lower.contains('حلل')) {
      return _analyzeText(input);
    } else if (lower.contains('+') || lower.contains('-') || lower.contains('*') || lower.contains('/')) {
      return _calculate(input);
    } else {
      return _chatResponse(input);
    }
  }
  
  String _generateCode(String input) {
    return '''
```dart
// Generated by ${getActiveModel()['name']}
void main() {
  print("Hello from Giant Agent X!");
  List<int> numbers = [1, 2, 3, 4, 5];
  int sum = numbers.reduce((a, b) => a + b);
  print("Sum: \$sum");
}
```
''';
  }
  
  String _generateWebsite(String input) {
    return '''
```html
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Giant Agent</title>
<style>
body{font-family:system-ui;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;display:flex;justify-content:center;align-items:center}
.card{background:white;border-radius:24px;padding:48px;max-width:500px;text-align:center}
h1{color:#667eea}button{background:#667eea;color:white;border:none;padding:12px 32px;border-radius:40px;cursor:pointer}
</style>
</head>
<body>
<div class="card">
<h1>Giant Agent X</h1>
<p>Created by AI</p>
<button onclick="alert('Hello!')">Click Me</button>
</div>
</body>
</html>
```
''';
  }
  
  String _analyzeText(String input) {
    final text = input.replaceAll(RegExp(r'analyze|حلل'), '').trim();
    if (text.isEmpty) return 'Please provide text to analyze';
    
    return '''
**Analysis Results**

Text: ${text.length > 100 ? text.substring(0, 100) + '...' : text}
Words: ${text.split(' ').length}
Characters: ${text.length}

Quality: ${text.length > 200 ? 'Excellent' : text.length > 100 ? 'Good' : 'Short'}
''';
  }
  
  String _calculate(String input) {
    try {
      if (input.contains('+')) {
        final parts = input.split('+');
        final a = double.parse(parts[0].trim());
        final b = double.parse(parts[1].trim());
        return 'Result: ${a + b}';
      } else if (input.contains('-')) {
        final parts = input.split('-');
        final a = double.parse(parts[0].trim());
        final b = double.parse(parts[1].trim());
        return 'Result: ${a - b}';
      } else if (input.contains('*')) {
        final parts = input.split('*');
        final a = double.parse(parts[0].trim());
        final b = double.parse(parts[1].trim());
        return 'Result: ${a * b}';
      } else if (input.contains('/')) {
        final parts = input.split('/');
        final a = double.parse(parts[0].trim());
        final b = double.parse(parts[1].trim());
        if (b == 0) return 'Error: Division by zero';
        return 'Result: ${a / b}';
      }
    } catch (e) {
      return 'Error in calculation';
    }
    return 'Please write: 5+3';
  }
  
  String _chatResponse(String input) {
    return "I understand your query. How can I help you further?";
  }
}
